name: hino_driver_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_svg: 2.0.10+1
  google_fonts: 6.2.1
  iconsax: 0.0.8
  equatable: 2.0.5
  easy_localization: 3.0.6
  shared_preferences: 2.2.3
  get_it: 7.7.0
  camera: 0.10.5+9
  shimmer: 3.0.0
  google_maps_flutter: 2.6.1
  sliding_up_panel: 2.0.0+1
  http: 1.2.1
  flutter_polyline_points: 2.0.0
  geocoding: 3.0.0
  permission_handler: 11.3.1
  path_provider: 2.1.3
  geolocator: ^7.0.3
  dio: 5.4.3+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/response_helpers/
  uses-material-design: true

